### PR TITLE
feat: add auto refresh if token is expired

### PR DESCRIPTION
**Pull request by NMathar**
some additions to handle autorefresh if token is expired. my tetsts with directus 9.5.2 worked well.
  

## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes (if not applicable, please state why)

### CODE REVIEW

**Comment by Intevel** [comment]
Hey @NMathar, thanks for your PR. Can you please run 'yarn lint' and push your changes?

**Comment by NMathar** [comment]
@Intevel eslint was not working correctly. i fixed it with some rules that has most of the files. i hope this is ok for you.

**Comment by Intevel** [comment]
Thanks, but now there are more thant 15 Files changed :/
Maybe discard your changes and do it again. Disable your formatter

**Comment by NMathar** [comment]
Maybe i have to explain a bit here. Yes thats bad that so many files are changed but i or you have to add some more eslint rules because every IDE or programmer brings his own code style into your project. to prevent this you have to add some eslint rules to your code. i added some that leave most of the code untouched. its up to you how you handle this i can revert my changes and add only some lines but its really annoying for me to revert every time my code changes.

i have testet your project with a complete clean setup and every time the editor formats different to your code style you need lint rules and a lint fix command for this.

**Comment by NMathar** [comment]
@Intevel so now only the codeblocks changes. i dont know what to add to documentation. i added only the function that the token is refreshed if login is not expired.

**Comment by AndreyKindin** [comment]
hi, is there a relese date for this function?

**Pull request closed without merging**
